apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-app-deployment
spec:
  selector:
    matchLabels:
      app: happyapp
  replicas: 2
  template:
    metadata:
      labels:
        app: happyapp
    spec:
      containers:
        - name: happyappcontainer
          image: happyappimg
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
