apiVersion: v1
kind: Pod
metadata:
  name: happyapppod
  labels:
    app: happyapp
spec:
  containers:
    - name: happyappcontainer
      image: happyappimg
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
